### ISSUE TITLE
首先非常感谢作者的alert，其次在表格中设置did点击事件时，会变得不灵敏

### ISSUE THREAD

**Issue by kuangtao22** [wxxsw/GSAlert#1]
在uitableview的代理方法didSelectRowAtIndexPath中添加GSAlert，每当第一次点击会没有反应，要连续点击两次才会正确跳出alert框，希望作者能看下

**Comment by wxxsw** [comment]
@kuangtao22 你好，很抱歉这么晚回复你。

我在我的demo中尝试在UITableView的didSelectRowAtIndexPath方法中调用GSAlert，每次点击时都能正常弹出Alert框，实验代码如下

``` swift
override func tableView(tableView: UITableView, didSelectRowAtIndexPath indexPath: NSIndexPath) {
    self.showAlert(.Alert, title: "标题", message: nil, sourceView: view, actions: [
       AlertAction(title: "确认", type: .Default, handler: nil),
       AlertAction(title: "取消", type: .Cancel, handler: nil)
    ])
}
```

是否有自定义的手势覆盖了didSelect方法，或者你没有在主线程中调用GSAlert？

你能提供更多的信息或者一个demo吗，让我知道如何帮助你。

**Comment by wxxsw** [comment]
Hi，不知道你的问题是否依然存在，我先将问题Close了，如果你依然有问题，可以Reopen，谢谢！
